# Pre-commit configuration to enforce basic hygiene and prevent secret leaks
# Install pre-commit via uv:
#   uv tool install pre-commit --with pre-commit-uv --force-reinstall
# Then enable hooks:
#   pre-commit install
# Run on all files (first time may modify files):
#   pre-commit run --all-files

minimum_pre_commit_version: "2.20.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: detect-private-key

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        args: ["--no-banner", "--redact"]
